# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

url: ""
name: Álvaro Orduna León
slogan: Passionate about understanding the world around me
description:
  "A place where I show my work and effort,
  comment on the issues that matter to me
  and share my experience."

social:
  email: alvaro.orduna.92@gmail.com
  facebook: AlvaroOrdunaLeon
  github: AlvaroOrduna
  google: ÁlvaroOrdunaLeón
  linkedin: alvaroordunaleon
  twitter: AlvaroOrduna

sass:
  style: compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
